### ISSUE TITLE
Cannot find module 'unplugin-vue-components/vite'

### ISSUE THREAD

**Issue by weeksun23** [antfu/unplugin-vue-components#172]
Version information:
```
"unplugin-vue-components": "^0.15.4",
"vite": "^2.4.4",
```
When I execute the 'npm run dev' command, the following error is reported
```
error when starting dev server:
Error: Cannot find module 'unplugin-vue-components/vite'
Require stack:
- D:\helloworld\workspace\insideoutside-mange-web\vite.config.ts
- D:\helloworld\workspace\insideoutside-mange-web\node_modules\vite\dist\node\chunks\dep-55830a1a.js
- D:\helloworld\workspace\insideoutside-mange-web\node_modules\vite\dist\node\cli.js
- D:\helloworld\workspace\insideoutside-mange-web\node_modules\vite\bin\vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\helloworld\workspace\insideoutside-mange-web\vite.config.ts:46:30)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.require.extensions.<computed> [as .ts] (D:\helloworld\workspace\insideoutside-mange-web\node_modules\vite\dist\node\chunks\dep-55830a1a.js:68630:20)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inside-outside-manage-web@1.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inside-outside-manage-web@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Must change ``import Components from "unplugin-vue-components/vite";`` 
to ``import Components from "unplugin-vue-components/dist/vite";``

Strangely, there is no error where I execute ``import Components from "unplugin-vue-components/vite"`` on the company's computer,but occur an error in home's computer.

My home's computer should use ``import Components from "unplugin-vue-components/dist/vite";``
My company's computer should use ``import Components from "unplugin-vue-components/vite";``

What is the problem? I've been confused for a long time.

**Comment by antfu** [comment]
What's your Node.js version?

**Comment by antfu** [comment]
Consider using v14 or above. v12 is no longer maintained.

**Comment by weeksun23** [comment]
> Consider using v14 or above. v12 is no longer maintained.

OK,thanks.
