### ISSUE TITLE
doesn't work after install

### ISSUE THREAD

**Issue by saulh502** [antfu/unplugin-vue-components#373]
doesn't work after install

failed to load config from /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts
error when starting dev server:
Error: Cannot find module 'unplugin-vue-components/vite'
Require stack:
- /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts
- /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js
- /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/cli.js
- /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts:114:27)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.require.extensions.<computed> [as .ts] (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61911:20)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadConfigFromBundledFile (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61919:17)
    at loadConfigFromFile (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61838:32)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async resolveConfig (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61365:28)
    at async createServer (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59772:20)

**Comment by MaloLebrin** [comment]
Can you give us more informations like your vite config, etc ...

**Comment by sxzz** [comment]
Reproduction repo please.
