### ISSUE TITLE
服务器端渲染引入css文件时候报错，SyntaxError: Unexpected token '^='

### ISSUE THREAD

**Issue by once2019** [antfu/unplugin-vue-components#392]
用单页面模式运行的时候完全正常，配置unplugin-vue-components按需自动导入，主要使用了antdv的一些组件
这是vite.config.js里关于插件的配置：
```
  plugins: [
    vue(),
    Components({
      resolvers: [
        AntDesignVueResolver({
          resolveIcons: true,
          cjs:true,
          // importStyle: 'less'
        }),
        ElementPlusResolver(),
      ],
    }),
  ],
```
我把项目改成ssr模式，就报了如下的错误，似乎是导入css的时候，css没有得到正确的处理，这里不知道该怎么进行了

```
5:24:10 PM [vite] Error when evaluating SSR module /src/components/home/Contact.vue:
/home/hxjq/Documents/vite-vue3/node_modules/ant-design-vue/lib/style/default.css:5
[class^=ant-]::-ms-clear,
      ^^

SyntaxError: Unexpected token '^='
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/hxjq/Documents/vite-vue3/node_modules/ant-design-vue/lib/input/style/css.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
5:24:10 PM [vite] Error when evaluating SSR module /src/views/Home.vue:
/home/hxjq/Documents/vite-vue3/node_modules/ant-design-vue/lib/style/default.css:5
[class^=ant-]::-ms-clear,
      ^^

SyntaxError: Unexpected token '^='
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/hxjq/Documents/vite-vue3/node_modules/ant-design-vue/lib/input/style/css.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
```

这里是server.js
```
const express = require('express');
const { createServer: createViteServer } = require('vite')
const fs = require('fs')
const path = require('path')


async function createServer(mode){
    const isProd = process.env.NODE_ENV === 'production' 
    const manifest = isProd ? require('./dist/client/ssr-manifest.json'):{}
    const app = express()
    
    let vite 
    if(isProd){
        app.use(require('compression')())
        app.use(
            require('serve-static')('./dist/client', {
                index: false
            })
        )
    }else {
        if(mode === 'html'){
            vite = await createViteServer({
                server:{
                    middlewareMode:'html'
                }
            })
        }else{
            vite = await createViteServer({
                server:{
                    middlewareMode:'ssr'
                }
            })
        }
        app.use(vite.middlewares)
    }
   

    app.get('*', async (req,res)=>{
        const url = req.originalUrl
        let template, render
        try{
            if(isProd){
                template = fs.readFileSync('./dist/client/index.html', 'utf-8')
                render = require('./dist/server/server-entry.js').render
            }else{
                template = fs.readFileSync(path.resolve(__dirname, 'index.html'),'utf-8')
                template = await vite.transformIndexHtml(url, template)
                render = (await vite.ssrLoadModule('/src/server-entry.js')).render
            }

            const [appHtml,preloadLinks] = await render(url,manifest)
            const html = template.replace('<!--ssr-outlet-->', appHtml).replace(`<!--preload-links-->`, preloadLinks)
            res.status(200).set({'content-type':'text/html'}).end(html)
        }catch(e){
            vite && vite.ssrFixStacktrace(e)
            console.log(e.stack)
            res.status(500).end(e.stack)
        }
    })

       
    app.listen(3000)
    console.log('node server start')
}

createServer('ssr')
```
这是 server-entry.js
```
import { createApp } from './main'
import { renderToString } from 'vue/server-renderer'

export async function render(url, manifest){
    const { app,router } = createApp()
    router.push(url)
    await router.isReady()
    const ctx = {}
    const html = await renderToString(app, ctx)
    const preloadLinks = renderPreloadLinks(ctx.modules, manifest)

    return [html, preloadLinks]
}
```

**Comment by l1shu** [comment]
+1

**Comment by sxzz** [comment]
Seems not the scope of this plugin. At least, you should provide a reproduction repo...
https://antfu.me/posts/why-reproductions-are-required
