### ISSUE TITLE
Can not use element-plus directive v-loading in jsx?

### ISSUE THREAD

**Issue by jackchoumine** [antfu/unplugin-vue-components#541]
### Describe the bug

I wanna use v-loading from element-plus in jsx, 

```jsx
setup() {
  const loading = ref(true)
  setTimeout(() => {
    loading.value = !loading.value
  }, 5000)
  return () => <div v-loading={loading.value}></div>
}
```
Auto import by [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)  come into error:

```bash
runtime-core.esm-bundler.js:2774 Uncaught TypeError: Cannot read properties of undefined (reading 'deep')
    at withDirectives (runtime-core.esm-bundler.js:2774:17)
    at Proxy.<anonymous> (UseButton.tsx:11:1)
```
After import element-plus global, work fine.

[reproduction repo](https://github.com/jackchoumine/delightful-vue3-vite-project)

### Reproduction

in my repo

### System Info

```Shell
System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 3.72 GB / 15.79 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 78.0.3904.108
    Edge: Spartan (44.19041.1.0)
    Internet Explorer: 11.0.19041.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jackchoumine** [comment]
## related issues: 

[Open element-plus directive error](https://github.com/antfu/unplugin-vue-components/issues/183)

solution: import it in main.js
```js
import { ElLoading } from 'element-plus'
app.use(ElLoading)
```
