### ISSUE TITLE
vant组件引入后报错

### ISSUE THREAD

**Issue by 13075239117** [antfu/unplugin-vue-components#561]
### Describe the bug

1:08:04 [vite] Internal server error: Failed to resolve import "vant/es" from "src\pages\home\index.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/jokey/jokey-vue3-ts/src/pages/home/index.vue:9:38
  7  |  import { defineComponent as _defineComponent } from "vue";
  8  |  import { testStore } from "@/store/test";
  9  |  import { Button as VanButton } from "vant/es";
     |                                       ^
  10 |  const _sfc_main = /* @__PURE__ */ _defineComponent({
  11 |    __name: "index",
      at formatError (file:///D:/jokey/jokey-vue3-ts/node_modules/.pnpm/vite@3.2.4_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39975:46)
      at TransformContext.error (file:///D:/jokey/jokey-vue3-ts/node_modules/.pnpm/vite@3.2.4_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39971:19)
      at normalizeUrl (file:///D:/jokey/jokey-vue3-ts/node_modules/.pnpm/vite@3.2.4_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36839:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (file:///D:/jokey/jokey-vue3-ts/node_modules/.pnpm/vite@3.2.4_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36972:47)
      at async Object.transform (file:///D:/jokey/jokey-vue3-ts/node_modules/.pnpm/vite@3.2.4_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40228:30)
      at async loadAndTransform (file:///D:/jokey/jokey-vue3-ts/node_modules/.pnpm/vite@3.2.4_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36615:29)

### Reproduction

<route lang="yaml"> { name: "test", meta: { requiresAuth: false } } </route> <template>   <div class="a">        <van-button type="primary" />   </div> </template>  <script setup lang="ts"> import { testStore } from '@/store/test'; const setName = () => {   store.setName("33")  } onMounted(() => {   console.log(useRoute().meta);  }) const store = testStore() </script>  <style lang="less" scoped src="./index.less"></style>

### System Info

```Shell
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "path";
import Pages from "vite-plugin-pages";
import Layouts from "vite-plugin-vue-layouts";
import AutoImport from "unplugin-auto-import/vite";
import { createSvgIconsPlugin } from "vite-plugin-svg-icons";
import ViteImages from "vite-plugin-vue-images";
import {
  AntDesignVueResolver,
  ElementPlusResolver,
  VantResolver,
} from "unplugin-vue-components/resolvers";
import windicss from "vite-plugin-windicss";
import Components from "unplugin-vue-components/vite"; //当前提及内容
function resolve(dir) {
  return path.join(__dirname, dir);
}

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      "@": resolve("./src"),
      "@components": resolve("./src/components"),
      "@pages": resolve("src/pages"),
      "@utils": resolve("src/utils"),
      "@router": resolve("src/router/index"),
    },
    extensions: [".js", ".json", ".ts", ".vue"],
  },
  css: {
    preprocessorOptions: {
      less: {
        // modifyVars: {
        //     hack: `true; @import (reference) "${path.resolve("src/assets/css/base.less")}";`,
        // },
        javascriptEnabled: true,
      },
    },
  },
  plugins: [
    vue(),
    Pages({
      importMode: "async",
      extendRoute(route) {
        if (route.path === "/") return { ...route, redirect: "home" };
      },
    }),
    Layouts({
      layoutsDirs: "src/layouts",
      defaultLayout: "index",
    }),
    windicss(),
    AutoImport({
      imports: ["vue", "vue-router", "pinia"],
      dts: "src/auto-imports.d.ts",
      resolvers: [VantResolver()],
      // dirs: ["./src/utils/composables/**"],
    }),
    Components({
      include: [/\.vue$/, /\.vue\?vue/, /\.tsx$/, /\.ts$/],
      resolvers: [
        VantResolver(),
        AntDesignVueResolver(),
        ElementPlusResolver(),
      ],
      // directoryAsNamespace: true,
    }),

    createSvgIconsPlugin({
      iconDirs: [path.resolve(process.cwd(), "src/assets/svg")],
      symbolId: "icon-[dir]-[name]",
      // svgoOptions: true,
    }),
    ViteImages({
      // Relative paths of image search directories
      dirs: ["src/assets/img"],

      // valid image extensions
      extensions: ["jpg", "jpeg", "png", "svg", "webp"],

      // Override default behavior of name -> image path resolution
      customResolvers: [],

      // Override Regex that searches for variables to replace. MUST include group
      customSearchRegex: "([a-zA-Z0-9]+)",
    }),
  ],
  server: {
    // ← ← ← ← ← ←
    host: "0.0.0.0", // ← 新增内容 ←
  },
});
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
If you are using auto-import
why line 9 exists?

1:08:04 [vite] Internal server error: Failed to resolve import "vant/es" from "src\pages\home\index.vue". Does the file exist?
Plugin: vite:import-analysis
File: D:/jokey/jokey-vue3-ts/src/pages/home/index.vue:9:38
7 | import { defineComponent as defineComponent } from "vue";
8 | import { testStore } from "@/store/test";
**9 | import { Button as VanButton } from "vant/es";**

**Comment by 13075239117** [comment]
> If you are using auto-import why line 9 exists?
> 
> 1:08:04 [vite] Internal server error: Failed to resolve import "vant/es" from "src\pages\home\index.vue". Does the file exist? Plugin: vite:import-analysis File: D:/jokey/jokey-vue3-ts/src/pages/home/index.vue:9:38 7 | import { defineComponent as defineComponent } from "vue"; 8 | import { testStore } from "@/store/test"; **9 | import { Button as VanButton } from "vant/es";**

no ，I put up the wrong message yesterday ，please look at it again. I fixed it

**Comment by azaleta** [comment]
![image](https://user-images.githubusercontent.com/22554452/204424001-11f25a2a-251e-4c40-8d22-96e669aee034.png)
`vant/es/button/style/index`
is a correct path.
Do you install vant correctly? Please check your node_module

**Comment by CJC824** [comment]
我也遇到这个错了 新建的项目

**Comment by 13075239117** [comment]
> ![image](https://user-images.githubusercontent.com/22554452/204424001-11f25a2a-251e-4c40-8d22-96e669aee034.png) `vant/es/button/style/index` is a correct path. Do you install vant correctly? Please check your node_module

...It doesn't work . It only works if I do that. ... i don't know why

import { Button as VanButton, Popup as VanPopup } from "vant";

this is my package.json
{
  "name": "jokey-vue3-ts",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "amfe-flexible": "^2.2.1",
    "axios": "^1.2.0",
    "crypto-js": "^4.1.1",
    "path-to-regexp": "^6.2.1",
    "pinia": "^2.0.26",
    "qs": "^6.11.0",
    "urijs": "^1.19.11",
    "vant": "^4.0.0",
    "vconsole": "^3.15.0",
    "vue": "^3.2.37",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@types/node": "^18.11.5",
    "@vitejs/plugin-vue": "^3.1.0",
    "less": "^4.1.3",
    "less-loader": "^11.1.0",
    "postcss": "^8.4.19",
    "postcss-pxtorem": "^6.0.0",
    "typescript": "^4.6.4",
    "unplugin-auto-import": "^0.11.5",
    "unplugin-vue-components": "^0.22.11",
    "vite": "^3.1.0",
    "vite-plugin-pages": "^0.27.1",
    "vite-plugin-svg-icons": "^2.0.1",
    "vite-plugin-vue-images": "^0.6.1",
    "vite-plugin-vue-layouts": "^0.7.0",
    "vite-plugin-windicss": "^1.8.8",
    "vue-tsc": "^0.40.4",
    "windicss": "^3.5.6"
  }
}

**Comment by 13075239117** [comment]
请问> 

解决了吗

**Comment by Sunxiaoyi1127** [comment]
![image](https://user-images.githubusercontent.com/38414477/207030688-592aeb0d-8b5a-4441-9497-120e4c213f6f.png)
漏掉了 .mjs 后缀，所以找不到 vant 里的 .mjs 模块
