### ISSUE TITLE
Not working with Nuxt3

### ISSUE THREAD

**Issue by dmaass-thing** [antfu/unplugin-vue-components#567]
### Describe the bug

I am currently in the situation that I have a kind of "base project" and another one which wants to overwrite components on a large scale.

To overwrite these components, I currently only see the possibility to use Nuxt 3 Layers. (Nuxt auto import does not support overwriting with the help of the "level" attribute anymore.

Since this would currently lead to major rebuilds in my projects, I would have liked to continue using this plugin for this. However, it does not work and I get the following error:
```
ERROR Cannot start nuxt:  Invalid plugin. src option is required: {"name":"unplugin-vue-components","enforce":"post","api":{},"vite":{}}                                                                           16:36:45

  at normalizePlugin (/Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:730:11)
  at /Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:745:61
  at Array.filter (<anonymous>)
  at addPlugin (/Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:745:47)
  at setup (/Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/nuxt@3.0.0_sass@1.56.2/node_modules/nuxt/dist/index.mjs:503:5)                                                                            16:36:44
  at normalizedModule (/Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:167:29)
  at async installModule (/Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (/Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/nuxt@3.0.0_sass@1.56.2/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (/Users/dennis.maass/projects/test/web/nuxt3/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
```
Reproduction link:
https://stackblitz.com/edit/nuxt-starter-sfvqhu?file=nuxt.config.ts

1. does anyone have an idea how i can fix this problem?
2. are there any plans to make this project work for Nuxt 3 as well?
3. Does anyone know Nuxt 3 native features to override components?

### Reproduction

https://stackblitz.com/edit/nuxt-starter-sfvqhu?file=nuxt.config.ts

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.91 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0
    Safari: 16.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markthree** [comment]
This is built-in in nuxt3, and no additional package is required 👉 [nuxt.com/docs/guide/directory-structure/components](https://nuxt.com/docs/guide/directory-structure/components)

**Comment by dmaass-diva-e** [comment]
Thanks for your answer @markthree 
Sorry but I'm not able to make it work. How is that supposed to work?

The following does not:
```
components: {
    global: true,
    dirs: ["~/components", "~/override-components"],
}
```
and the old Nuxt2 "level" attribute is not available anymore.
I already opened a feature request for that https://github.com/nuxt/framework/issues/9763

I don't see a solution to override component without the Nuxt 3 layers feature, but that results in a bigger rebuild.

**Comment by markthree** [comment]
@dmaass-diva-e hello，Do you want this effect 👉 [stackblitz-demo](https://stackblitz.com/edit/nuxt-starter-whs6rm?file=app.vue,components%2Ffoo.vue,nuxt.config.ts)。

I changed the order. It works 👇

```ts
components: {
    global: true,
    dirs: ['~/override-components', '~/components'],
}
```
But I haven't had time to browse the corresponding source code, which may have potential errors 🤔

**Comment by dmaass-diva-e** [comment]
Thank you very much @markthree 
I think you are right. The solution was probably much simpler than I thought.
I will test it and report back.

**Comment by dmaass-diva-e** [comment]
Yes, it's working 🚀
Thanks @markthree  🙂

**Comment by NarHakobyan** [comment]
this plugins works partially, it generates separate type definition files and editor stopping recognize nuxt's generated one.
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1781506/215434913-a34aa525-43cf-4f09-82ee-9f421f3fcb4a.png">

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1781506/215434977-ebfd9f2b-12f3-443f-b036-3897cc09e9d1.png">

But, TheHeader is any (is under components folder)

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1781506/215435023-b5d5af81-f3c5-49e2-8d57-cac4f3256677.png">

**Comment by everatch** [comment]
> this plugins works partially, it generates separate type definition files and editor stopping recognize nuxt's generated one.
I got the same issue.

The definition file output from Nuxt declare module 'vue`, but this plugin declare module '@vue/runtime-core`.
I tried manually changing the two files to the same module and both of then worked well!
How can i do for it with automatic creation?

**Comment by hcwhan** [comment]
> this plugins works partially, it generates separate type definition files and editor stopping recognize nuxt's generated one. <img alt="image" width="661" src="https://user-images.githubusercontent.com/1781506/215434913-a34aa525-43cf-4f09-82ee-9f421f3fcb4a.png">
> 
> <img alt="image" width="661" src="https://user-images.githubusercontent.com/1781506/215434977-ebfd9f2b-12f3-443f-b036-3897cc09e9d1.png">
> 
> But, TheHeader is any (is under components folder)
> 
> <img alt="image" width="661" src="https://user-images.githubusercontent.com/1781506/215435023-b5d5af81-f3c5-49e2-8d57-cac4f3256677.png">

same issue

**Comment by markthree** [comment]
> this plugins works partially, it generates separate type definition files and editor stopping recognize nuxt's generated one. 
> But, TheHeader is any (is under components folder)

Make everything simple，Just use [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) if you need component library 👇

```ts
import Components from "unplugin-vue-components/vite";
import { ArcoResolver } from "unplugin-vue-components/resolvers";

export default defineNuxtConfig({
  components: false, // Turn off native nuxt option
  vite: {
    plugins: [
      Components({
        dts: true,
        dirs: ["components"],
        directoryAsNamespace: true,
        resolvers: [ArcoResolver()],
      }),
    ],
  },
});
```
![image](https://user-images.githubusercontent.com/36569518/224669206-b2089ff4-0364-4620-9782-e439e98394d4.png)
![image](https://user-images.githubusercontent.com/36569518/224669279-ebbc7d1c-da65-4d9b-8006-d218bf1664b1.png)

types are available for ts。

@NarHakobyan @hcwhan @everatch

**Comment by hcwhan** [comment]
@markthree  use this nuxt built-in components fail
now,  reference https://nuxt.com/docs/guide/directory-structure/components#library-authors use `modules`
For example, I use naive-ui .
add `/modules/naiveui.ts`
```ts
import klawSync from 'klaw-sync'

import { defineNuxtModule, createResolver, addComponent } from '@nuxt/kit'

export default defineNuxtModule({
  hooks: {
    'components:dirs'() {
      const { resolve } = createResolver(import.meta.url)

      const scanDir = resolve('../node_modules/naive-ui/es')
      const files = klawSync(scanDir, { nodir: true })
      const componentFiles = files
        .filter((item) => {
          const relativePath = item.path.slice(scanDir.length + 1)
          return /^[a-z]+\/src\/[A-Z]\w+\.js$/.test(relativePath)
        })
        .map((item) => item.path)

      for (const filePath of componentFiles) {
        const fileName = filePath.replace(/^.*\/(\w+)\.js$/, '$1')
        addComponent({
          name: `N${fileName}`,
          filePath,
        })
      }
    },
  },
})

```

**Comment by hcwhan** [comment]
@NarHakobyan @everatch
