### ISSUE TITLE
[Bug Report] vite-ssg with ElementPlusResolver()

### ISSUE THREAD

**Issue by YunYouJun** [antfu/unplugin-vue-components#58]
When i use **vite-ssg** with **vite-plugin-componsnts** `customComponentResolvers: [ElementPlusResolver()]`.
I will get `Cannot use import statement outside a module`.

```bash
/Users/yunyou/github/pages/sponsors/node_modules/.pnpm/element-plus@1.0.2-beta.46_vue@3.0.11/node_modules/element-plus/es/el-tabs/index.js:1
(function (exports, require, module, __filename, __dirname) { import { defineComponent, inject, getCurrentInstance, ref, watch, nextTick, openBlock, createBlock, computed, onUpdated, onMounted, onBeforeUnmount, h, provide, Fragment } from 'vue';
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:101:7)
    at p._moduleCompile (/Users/yunyou/github/pages/sponsors/node_modules/.pnpm/jiti@1.10.1/node_modules/jiti/dist/v8cache.js:2:3154)
    at Module.o._compile (/Users/yunyou/github/pages/sponsors/node_modules/.pnpm/jiti@1.10.1/node_modules/jiti/dist/v8cache.js:2:2705)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at n (/Users/yunyou/github/pages/sponsors/node_modules/.pnpm/jiti@1.10.1/node_modules/jiti/dist/v8cache.js:2:2472)
    at Module.<anonymous> (/Users/yunyou/github/pages/sponsors/.vite-ssg-temp/main.js:13:29)
    at Module.o._compile (/Users/yunyou/github/pages/sponsors/node_modules/.pnpm/jiti@1.10.1/node_modules/jiti/dist/v8cache.js:2:2778)
```

---

## Steps to reproduce

Use [vitesse](https://github.com/antfu/vitesse/).

```sh
npx degit antfu/vitesse my-vitesse-app
cd my-vitesse-app
npm i
```

Add [element-plus](https://element-plus.org/).

```sh
npm add element-plus
```

Config element-plus.

```ts
// src/modules/element.ts
import { UserModule } from "~/types";

import ElementPlus from "element-plus";
import "element-plus/lib/theme-chalk/index.css";

export const install: UserModule = ({ app }) => {
  app.use(ElementPlus);
};
```

```ts
// vite.config.ts
export default defineConfig({
  ...
  ViteComponents({
    ...
    // auto import icons
    customComponentResolvers: [
      ElementPlusResolver()
    ],
  }),
  ...
})
```

```vue
// App.vue
<template>
  <router-view />
  <el-button>TEST</el-button>
</template>
```

At last, `npm run build`. We will get this error.

## My Solution

Remove `ElementPlusResolver()`, and it works.

## Other

https://github.com/antfu/vite-plugin-components/blob/5c0842971a75c4244da25a5bc6c57a9948165806/src/resolvers/element-plus.ts#L25

The export of element-plus is located in lib.

> https://github.com/element-plus/element-plus/blob/9b74a3dd03541e8aca369f5dd57be4305b26a326/package.json#L152

```json
// element-plus/package.json
{
  "main": "lib/index.js",
  "module": "lib/index.esm.js",
  "typings": "lib/index.d.ts",
  "unpkg": "lib/index.js",
  "style": "lib/theme-chalk/index.css",
}
```

And element-plus support on-demand import by `vite-plugin-style-import`. It use `element-plus/lib/${name}`.

> https://element-plus.org/#/zh-CN/component/quickstart#an-xu-yin-ru

```ts
export default defineConfig({
  plugins: [
    vue(),
    styleImport({
      libs: [{
        libraryName: 'element-plus',
        esModule: true,
        ensureStyleFile: true,
        resolveStyle: (name) => {
          name = name.slice(3)
          return `element-plus/packages/theme-chalk/src/${name}.scss`;
        },
        resolveComponent: (name) => {
          return `element-plus/lib/${name}`;
        },
      }]
    })
  ]
})
```

So we can change `element-plus/es/el-${partialName}` to `element-plus/lib/el-${partialName}`.

If you think I am right, just tell me and I will create a PR for it.

**Comment by Fanna1119** [comment]
Also have issue with this.
I get the following error.
>GET http://localhost:3333/@id/@vite-icons/el/empty net::ERR_ABORTED 404 (Not Found)

**Comment by LittleSound** [comment]
@antfu  I am also experiencing this problem. When will this be fixed please?

**Comment by Mhdi-kr** [comment]
have u solved it yet? @LittleSound
