### ISSUE TITLE
bootstrap-vue-next: import_resolvers.BootstrapVueNextResolver is not a function

### ISSUE THREAD

**Issue by Sibiryakanton** [antfu/unplugin-vue-components#602]
### Describe the bug

Hello!
I copied config from bootstrap-vue-next documentation:
https://bootstrap-vue.github.io/bootstrap-vue-next/getting-started/#installation-vue-js

And got the error when i trying run the project:
```
failed to load config from /home/anton/Django-u/vue_bootstrap_bugcase/vite.config.js
error when starting dev server:
TypeError: (0 , import_resolvers.BootstrapVueNextResolver) is not a function
    at Object.<anonymous> (/home/anton/Django-u/vue_bootstrap_bugcase/vite.config.js:45:65)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object._require.extensions.<computed> [as .js] (file:///home/anton/Django-u/vue_bootstrap_bugcase/node_modules/vite/dist/node/chunks/dep-9912c491.js:62318:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (file:///home/anton/Django-u/vue_bootstrap_bugcase/node_modules/vite/dist/node/chunks/dep-9912c491.js:62326:21)
    at loadConfigFromFile (file:///home/anton/Django-u/vue_bootstrap_bugcase/node_modules/vite/dist/node/chunks/dep-9912c491.js:62184:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
What am I do wrong?
Base vue 3 project with setup published in repository (see url in Reproduction field).

### Reproduction

https://gitlab.com/Sibiryakanton/vue_unplugin_bugcase

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 22.98 GB / 31.27 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.12.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 109.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lishaobos** [comment]
hi, update unplugin-vue-components to 0.24.0, it is worked.
